# Database configuration file for development and testing w/ ActiveRecord or DataMapper/DataObjects.

# NOTE: Our Capistrano deployment replaces this file with a configuration file pulled in from outside the repository.
# NOTE: This defines the default DataMapper connection; other connections can be defined.


default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: zztop_development
  user: postgres
  password: password
  host: localhost

test: &test
  <<: *default
  database: zztop_test
  password: Tropicana
  host: localhost

cucumber:
  <<: *test
