# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  TWILIO_ACCOUNT_SID: AC91a8c967e11e4559e3cb566dc4fafd01
  TWILIO_AUTH_TOKEN: be5bc802a142c0d0b07c5c7a818c49fd

development:
  <<: *default
  secret_key_base: 69bb5b761137b60e6d99634c1b2ad7f205bd02059fb11f1e107ff05a77d7a75f6eb9efd9a4680f1f5ecd48ac11eee436d21c6af6c4ce5eab95cea89ff1bb8e2a

test:
  <<: *default
  secret_key_base: d054bafa270a4e750cb79bbe48337a6aee16e6a82c0a5ec54c7f54dc8890518b8c038b3e96b8ff407b38a87dc04bb21175bbfd00d56088e5738b42c00f7f012d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
